USE CADASTRO;

INSERT INTO PESSOAS 
(ID_PESSOAS, NOME, NASCIMENTO, SEXO, PESO, ALTURA, NACIONALIDADE)
VALUES
(DEFAULT, 'CLAÚDIO', '1975-12-15', 'M', 70.2, 1.75, DEFAULT),
(DEFAULT, 'Cio', '1995-03-17', 'M', 70.2, 1.75, DEFAULT);
-- QUANDO A ORDEM É EXATAMENTE A MESMA, NÃO PRECISA INFORMAR
-- OS CAMPOS NO ÍNICIO
-- INSERT INTO PESSOAS VALUES
SELECT * FROM PESSOAS;

-- ID COM AUTO_INCREMENT, CADA VEZ QUE UMA PESSOA SE CADASTRE
-- O SISTEMA DEFINE AUTOMATICAMENTE COMO  CÓD VAI SER EXECUTADO
-- ENTÃO NÃO PRECISA DO ID, É AUTO_INCREMENT

describe pessoas;

